pipeline:
  name: python-ci-demo                   # Friendly name of your pipeline
  identifier: python_ci_demo             # Unique ID (used by Harness)
  projectIdentifier: JuanPythonPipe      # <-- Replace with your Harness Project ID
  orgIdentifier: default                 # <-- Replace with your Organization ID
  tags: {}                               # Optional metadata tags

  # Code repository setup
  properties:
    ci:
      codebase:
        connectorRef: github_connector   # <-- Replace with your GitHub Connector name
        build: <+input>                  # Harness lets you choose branch/tag at runtime

  # ---- Pipeline Stages ----
  stages:
    - stage:
        name: Build_Test_Push            # Stage name visible in the UI
        identifier: Build_Test_Push
        type: CI                         # Continuous Integration stage type
        spec:
          cloneCodebase: true            # Harness will clone your Git repo automatically

          # --- Cloud Build Environment ---
          infrastructure:
            type: Hosted                 # Using Harness Cloud Build (no delegate needed)
            spec:
              platform:
                os: Linux
                arch: Amd64              # 64-bit Linux runners
              runtime:
                type: Cloud              # Harness-hosted environment, fully managed

          # --- The CI Steps ---
          execution:
            steps:
              # 1️⃣ Install dependencies and run tests
              - run:
                  name: Install Test
                  identifier: Install_Test
                  shell: Sh
                  command: |
                    python -m venv venv
                    . venv/bin/activate
                    pip install -U pip
                    pip install -r requirements.txt
                    pytest -q

              # 2️⃣ Build and push Docker image to DockerHub
              - buildAndPushDockerRegistry:
                  name: Build and Push Docker Image
                  identifier: Build_Push
                  spec:
                    connectorRef: dockerhub_connector   # <-- Replace with your DockerHub connector
                    repo: jcontin03/harness-ci-demo
                    tags:
                      - latest
                      - <+pipeline.sequenceId>           # Auto-incremented run number
                    dockerfile: Dockerfile                # Dockerfile path (root)
                    context: .                            # Build context (current dir)

          # --- Optional caching to speed up builds ---
          caching:
            enabled: true
            key: python-ci-demo-cache