pipeline:
  name: python_ci_demo
  identifier: python_ci_demo
  projectIdentifier: PythonCIPipeline
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        build: <+input>
  stages:
    - stage:
        name: main
        identifier: main
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install and Test
                  identifier: Install_and_Test
                  spec:
                    shell: Sh
                    workingDirectory: /harness
                    command: |
                      set -eu
                      echo "Current directory: $(pwd)"
                      echo "Contents:"
                      ls -la || true

                      # Prefer python3 if available
                      if command -v python3 >/dev/null 2>&1; then PY=python3; else PY=python; fi
                      $PY --version || true

                      # Create and activate virtual environment
                      $PY -m venv venv
                      . venv/bin/activate

                      # Install dependencies and run tests
                      python -m pip install -U pip
                      pip install -r requirements.txt
                      pytest -q
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Docker Image
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub_connector
                    repo: jcontin03/harness-ci-demo
                    tags:
                      - latest
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
